[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"  # Версия Solidity (можно изменить)
optimizer = true          # Включить оптимизатор
optimizer_runs = 200      # Количество прогонов оптимизатора (для баланса gas/размера)

# Настройки тестов
[fmt]                    # Форматирование кода
line_length = 120        # Длина строки
tab_width = 4            # Размер табуляции

[fuzz]                   # Настройки фаззинга (если используешь)
runs = 256               # Количество прогонов
max_test_rejects = 65536 # Максимальное количество отвергнутых входных данных

# Дополнительные пути для импортов (если используешь библиотеки)
allow_paths = ["src", "lib"]